// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbdxNscIitfqCTFU3tqm0aAMf_Wpd_S8',
    appId: '1:985039980689:web:fecb8ba5a98aa964749730',
    messagingSenderId: '985039980689',
    projectId: 'vallidator',
    authDomain: 'vallidator.firebaseapp.com',
    storageBucket: 'vallidator.appspot.com',
    measurementId: 'G-JG5JK6GYL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqZYJGq13nqXKj3CUdUL1Latru81NyUY',
    appId: '1:985039980689:android:f328c07af5a4cb86749730',
    messagingSenderId: '985039980689',
    projectId: 'vallidator',
    storageBucket: 'vallidator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgVqYDTYOEtn5HCarZC0CS84F16jjFBRE',
    appId: '1:985039980689:ios:fcab06a5988c5936749730',
    messagingSenderId: '985039980689',
    projectId: 'vallidator',
    storageBucket: 'vallidator.appspot.com',
    iosBundleId: 'br.com.vallidator.vallidator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgVqYDTYOEtn5HCarZC0CS84F16jjFBRE',
    appId: '1:985039980689:ios:cb1d4e0a5432aa85749730',
    messagingSenderId: '985039980689',
    projectId: 'vallidator',
    storageBucket: 'vallidator.appspot.com',
    iosBundleId: 'br.com.vallidator.vallidator.RunnerTests',
  );
}
